#pragma once

#include "PitchEngine.h"
// Generated by Corrosion's corrosion_add_cxxbridge (CMakeLists.txt) from
// crates/pitch-core-ffi/src/lib.rs. Note the include path is named after
// the CMake cxx-bridge target ("pitch_core_ffi_cxx"), not the crate's own
// path ("pitch-core-ffi/src/lib.rs.h") the way plain cxx-build would name
// it — confirmed by inspecting the actual generated file tree under
// build/corrosion_generated/cxxbridge/, not assumed from cxx's own docs,
// since Corrosion's wrapping changes this specific detail.
#include "pitch_core_ffi_cxx/lib.h"

namespace pitchzazz
{

/// Wraps pitch-core (the Rust engine) behind the PitchEngine interface,
/// via the cxx bridge in crates/pitch-core-ffi. This is what makes the
/// hot-swap (docs/ROADMAP.md Phase 3) an actual Rust-vs-C++ comparison
/// rather than two C++ implementations — the same algorithm, run through
/// the actual Rust crate, not a C++ re-implementation of it.
class RustCorrectorEngine : public PitchEngine
{
public:
    explicit RustCorrectorEngine (const EngineConfig& config);

    const char* getName() const noexcept override { return "Phase Vocoder (Rust FFI)"; }
    void setScale (Scale newScale) noexcept override;
    [[nodiscard]] CorrectionResult process (const std::vector<float>& samples, double sampleRate) override;
    [[nodiscard]] int getLatencySamples() const noexcept override { return (int) pitchzazz_rust::latency_samples (*corrector); }

private:
    rust::Box<pitchzazz_rust::RustCorrector> corrector;
    int blockSize;
};

} // namespace pitchzazz
